### ISSUE TITLE
java.lang.NumberFormatException: Cannot parse null string

### ISSUE THREAD

**Issue by sav7ng** [Jamling/SmartIM4IntelliJ#101]
![图片](https://github.com/user-attachments/assets/d55f913a-fad6-4576-bbb2-0055e5bfe3c9)
![图片](https://github.com/user-attachments/assets/35ad2333-822d-451c-bbfe-e442f482eda1)

---

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cn.ieclipse.smartim.actions.HideContactAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cn.ieclipse.smartqq.intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

---

IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024

Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by Jamling** [comment]
插件更新到最新的3.0.1版本就行了

**Comment by sav7ng** [comment]
@Jamling 可能需要更新以下代码版本

![图片](https://github.com/user-attachments/assets/cc868a39-29ef-46c5-8050-18eca0dbc01e)

**Comment by sav7ng** [comment]
```
// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version = 'IU-2023.3.6'
}
patchPluginXml {
    sinceBuild = '223'
    untilBuild = '241.*'
}
```

**Comment by Jamling** [comment]
> ```
> // See https://github.com/JetBrains/gradle-intellij-plugin/
> intellij {
>     version = 'IU-2023.3.6'
> }
> patchPluginXml {
>     sinceBuild = '223'
>     untilBuild = '241.*'
> }
> ```

已更改为默认兼容未来的IDE版本。已上传插件应用市场，可以下载了

**Comment by sav7ng** [comment]
@Jamling 已解决，感谢
