### ISSUE TITLE
登录微信当微信出现安全验证时候会报空指针

### ISSUE THREAD

**Issue by yanceysong** [Jamling/SmartIM4IntelliJ#102]
![86006305c4b57d7b18de19244bed30af75a0fc14be25ff575742f4113943bbfdQzpcVXNlcnNcc29uZ3lhbmcyXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxNDY5MDg2MDY5X3YyXEltYWdlRmlsZXNcNzE2NjQ1MTZcMjQ4OTUxMjY0ODVfMTUyMzk1Mjc2MjIyX0lNR180ODY0LlBORy5KUEc=](https://github.com/user-attachments/assets/d3b0a22a-d1b6-43ff-a996-218707750d67)
我下载了smartIm的swing版本，报错日志如下

![image](https://github.com/user-attachments/assets/dac28281-56f6-4866-9eca-7433c80bf948)
界面显示如下
![image](https://github.com/user-attachments/assets/bafca40f-87f5-4c62-bfa5-478444deac82)

**Comment by Jamling** [comment]
兄弟，登录url是微信返回的，日志中未打印微信原始响应，我暂时也不清楚，如果你熟悉Java，可以自行在SmartIM项目中开启调试进一步分析。如果不方便，可以加我微信outernetsoft，到时候我开启调试，需要你配合扫码登录。
