### ISSUE TITLE
微信二维码显示失败，提示java.lang.RuntimeException: javax.net.ssl.SSLProtocolException: handshake alert: unrecognized_name

### ISSUE THREAD

**Issue by Cai-Go** [Jamling/SmartIM4IntelliJ#12]
![image](https://user-images.githubusercontent.com/7565399/32837590-1bd9219c-ca49-11e7-96d6-8bb807536a44.png)

**Comment by Jamling** [comment]
微信需加JVM运行参数，如快捷方式目标指向：`E:\Android\eclipse\eclipse.exe -nl=en -Djsse.enableSNIExtension=false`，注意，exe所在的路径不能带空格

**Comment by solodoit** [comment]
这样可真不好

**Comment by Jamling** [comment]
@solodoit 木有办法，微信的https有问题。只能禁用java 的jsse.enableSNIExtension

**Comment by qq645381995** [comment]
mac  还没有装 eclipse  怎么办？ @Jamling

**Comment by Jamling** [comment]
@qq645381995 将我的示例快捷方式目标替换成你自己的，比如 /path/toyour_idea.exe

**Comment by qq645381995** [comment]
mac  没有 exe

**Comment by Jamling** [comment]
@qq645381995 这个你自己百度一下子吧。类似windows

**Comment by qq645381995** [comment]
@Jamling   你说这个  要在哪里设置？

**Comment by Jamling** [comment]
@qq645381995 你可以添加一个快捷方式指向可运行程序，再加运行参数。实在不行就写个命令脚本吧。

**Comment by qq645381995** [comment]
算了 不搞了

**Comment by z2700589** [comment]
不懂怎么设置

**Comment by sth0409** [comment]
在bin文件夹下的   studio64.exe.vmoptions  中添加 -Djsse.enableSNIExtension=false 就行了

**Comment by Jamling** [comment]
@sth0409 👍 🥇 感谢！我马上更新到README中

**Comment by Mr-Guan** [comment]
@Jamling @qq645381995 
Mac电脑只需要打开:
1.Applications
2.找到【IntelliJ IDEA】
3.右击【显示包内容】
4.打开：Contents--->bin
5.使用Atom/其他 编辑【idea.vmoptions】尾部加入：-Djsse.enableSNIExtension=false
6. reset
完毕~

**Comment by Jamling** [comment]
@Mr-Guan 谢谢~ 6, reset是什么意思？是idea重启吗？

**Comment by raysonmeng** [comment]
@Mr-Guan 
Mac pycharm 的 Contents--->bin 另种没有 idea.vmoptions 啊 只有一个 pycharm.vmoptions

**Comment by Jamling** [comment]
@raysonmeng pycharm就是pycharm.vmoptions，内容贴出来看看。
