### ISSUE TITLE
弹出的框，中文乱码

### ISSUE THREAD

**Issue by huekeyu** [Jamling/SmartIM4IntelliJ#16]

**Comment by Jamling** [comment]
可以描述具体一点吗？

**Comment by huekeyu** [comment]
我点击登录的时候是弹出了一个对话框，不过提示都是乱码的

**Comment by huekeyu** [comment]
我用的是win7 Android studio 3.0

**Comment by Jamling** [comment]
点击登录，弹出的是二维码窗口，此窗口显示的内容为二维码图片，如果二维码异常，才会显示文字提示信息。你的操作系统是中文的吧？

**Comment by huekeyu** [comment]
我的系统是win7旗舰版 Android studio没有使用中文的

**Comment by Jamling** [comment]
跟AS语言无关，只跟操作系统有关。都是中文的话，不应该出现乱码，源代码使用utf-8。我使用的是win7, AS 2.3.1一切正常

**Comment by huekeyu** [comment]
那会不会是不兼容as 3.0

**Comment by Jamling** [comment]
你登录的是QQ还是微信，AS中有没有创建工程？发个截图给我

**Comment by msdx** [comment]
同样乱码。
Ubuntu.
![2017-11-28 10-08-20](https://user-images.githubusercontent.com/1903422/33298934-240aeb86-d424-11e7-9e00-cc5c6e723153.png)

**Comment by Jamling** [comment]
@msdx 请问你的ubuntu系统默认什么编码方式，建议你新开一条issue：SmartIM设置界面乱码
