### ISSUE TITLE
微信的异常

### ISSUE THREAD

**Issue by z2700589** [Jamling/SmartIM4IntelliJ#18]
![tim 20171123153704](https://user-images.githubusercontent.com/22461898/33162371-2f37cea2-d064-11e7-8230-c418d22be10c.png)

能显示二维码了，但是一直显示超时。
当我登录以后，马上就掉线了。

**Comment by Jamling** [comment]
关闭一下，并且在手机上，手动退出微信网页版。然后过5秒再重试
