### ISSUE TITLE
怎么发送消息，没有按钮

### ISSUE THREAD

**Issue by Shyky** [Jamling/SmartIM4IntelliJ#24]

**Comment by Jamling** [comment]
1，先点击SmartIM中的设置图标进入设置
2，勾选"显示发送按钮（MAC上无法按Enter发送？）"
3，重新打开聊天窗口就看见了。

**Comment by Shyky** [comment]
我不是mac，是windows 10

**Comment by Shyky** [comment]
怎么跟你一起完善这个项目

**Comment by Shyky** [comment]
我也是做Android

**Comment by Shyky** [comment]
我看了很感兴趣

**Comment by Jamling** [comment]
本插件所有代码均开源，所以，你可以fork本项目并提交PR。
附：
1，本插件使用的聊天协议及中间层在[SmartIM](https://github.com/Jamling/SmartIM)
2，本插件适用于IntelliJ平台的IDE，包含但不限于AS
