### ISSUE TITLE
自己发送的消息会重复出现

### ISSUE THREAD

**Issue by lee1994522** [Jamling/SmartIM4IntelliJ#3]
如图：
![image](https://user-images.githubusercontent.com/11418562/29344436-6daa8c08-826a-11e7-824b-b4a763ed33cd.png)
这条消息是我发送的，而且只发送了一次，但出现了两次

**Comment by Jamling** [comment]
参考 #2 
确实是这样子的，在群聊和讨论组中，自己发出去的消息，SmartQQ将随机分配一个虚拟的QQ号发送回来。不清楚腾讯为啥这么设计。不过这样也好，可以清楚的知道，你发的消息已经发送成功了。
