### ISSUE TITLE
QQ二维码显示超时

### ISSUE THREAD

**Issue by waterWang** [Jamling/SmartIM4IntelliJ#36]
![image](https://user-images.githubusercontent.com/6082925/34940265-d3fa5c36-fa29-11e7-9989-f641269d5688.png)

**Comment by Jamling** [comment]
点登录了吗？

**Comment by waterWang** [comment]
登陆按钮在哪里？没看到啊

**Comment by waterWang** [comment]
![Uploading image.png…]()

**Comment by waterWang** [comment]
![image](https://user-images.githubusercontent.com/6082925/34968815-79c3cd2e-faa6-11e7-8523-0eac141713c2.png)

**Comment by waterWang** [comment]
![image](https://user-images.githubusercontent.com/6082925/34968830-9a796d30-faa6-11e7-967d-f04ed906a3da.png)

二维码很快就失效，还没来得及登陆

**Comment by Jamling** [comment]
QQ未设置连接超时，微信是10秒的超时。怎么都够你扫个码了。
估计是你操作不当。把连接先断开再重新登录扫码试试

**Comment by waterWang** [comment]
。。。就是QQ二维码失效，微信可以登陆

**Comment by sunqb** [comment]
二维码不显示，是否网络原因

**Comment by Jamling** [comment]
@sunqb 微信还是QQ？二维码窗口有错误提示的。日志中也有

**Comment by sunqb** [comment]
@Jamling 可以使用了，不过打开聊天窗口非常慢。然后我就卸载了。
