### ISSUE TITLE
这个需要怎样登出呢？

### ISSUE THREAD

**Issue by dev-emmon** [Jamling/SmartIM4IntelliJ#4]
登录之后无法进行登出操作？

**Comment by dev-emmon** [comment]
不对，好像点了 close 登出了，但是列表没清除！

**Comment by Jamling** [comment]
点击X (close) 登出，Recents没有清空不影响正常使用。

**Comment by dev-emmon** [comment]
嗯嗯，就不能第一时间知道是否已经登出了（也是在点了联系人看到日志才知道的），希望下个版本能有改进！

**Comment by Jamling** [comment]
连接断开，点击联系人是没有反应的（不会打开聊天窗口），清除Recents功能会与Recent排序会在后续版本中实现
