### ISSUE TITLE
如果把IDE Talk的功能搬到里面有价值

### ISSUE THREAD

**Issue by tonycody** [Jamling/SmartIM4IntelliJ#5]
IDE Talk 曾经有一个功能叫“Send Code Pointer”,如果能把这个功能搬到这里面，这个插件要火。

IDE Talk 自从 google talk 关闭了XMPP协议之后几乎就死了，又找不到替代品。

![image](https://user-images.githubusercontent.com/6773121/29447550-fc1eb386-8424-11e7-9bbc-35fe1d7614cd.png)

**Comment by Jamling** [comment]
非常不错的建议！ 昨天晚上还在想，这个插件既然是给开发者用的，那么应该添加一个发送项目文件的功能。与你所说的IDE talk应该类似，不过smart qq并不支持发送长文本内容。所以选择代码片段发送，如果代码过长，发送失败的概率极大。

**Comment by tonycody** [comment]
说明你之前并没用过IDE Talk 用过你就知道了。它并不是发送长文本，而是类名+位置

**Comment by tonycody** [comment]
![image](https://user-images.githubusercontent.com/6773121/29452214-15f4f7ee-8438-11e7-9b95-96d51fc5aafd.png)
参考！

**Comment by tonycody** [comment]
其实做4件事：
1.代码编辑器右键增加一个发送菜单项。
2.获取当前光标所有的类和当前光标所在的行信息
3.发送到QQ列表中的某个人
4.收到的人点这个内容跳转到指定的类的指定行~

**Comment by tonycody** [comment]
说白了，IDE Talk 的初忠就是为了定位代码~

**Comment by Jamling** [comment]
了解了，谢谢~
我想的是在资源树中，右击鼠标，然后点击“发送到SmartQQ”，直接将所选的文件发送对当前的聊天窗口中。

**Comment by Jamling** [comment]
![default](https://user-images.githubusercontent.com/5350591/29547016-419d7656-872a-11e7-8d50-1e306e5767ca.png)

Eclipse 版本已实现类似功能
:)

**Comment by tonycody** [comment]
加下微信吧，可以一起参与一下。tonycody
