### ISSUE TITLE
SmartIM设置界面乱码

### ISSUE THREAD

**Issue by youphp** [Jamling/SmartIM4IntelliJ#53]
<img width="1440" alt="qq20181022-164903 2x" src="https://user-images.githubusercontent.com/22139551/47284586-77ab2a00-d61a-11e8-92b0-8d10df0564bb.png">

**Comment by Jamling** [comment]
目测你的操作系统应该是MAC，首先确保你的系统中安装有中文字体（一般会有）。然后检查IntelliJ IDE的字体设置，换一个支持中文的字体。最后，如果没有的话，那自己手动安装一个中文字体吧。

**Comment by youphp** [comment]
嗯。。换了个中文字体就好了，不过要是能支持英文就更好了

**Comment by Jamling** [comment]
用QQ和微信的，基本上是咱中国人。懒得国际化了。

**Comment by youphp** [comment]
主要还是字体问题，喜欢的字体又不支持中文，设置一个中文字体又不喜欢
