### ISSUE TITLE
有意思的项目，但是为什么不用maven这类工具来管理依赖呢？

### ISSUE THREAD

**Issue by kenshinji** [Jamling/SmartIM4IntelliJ#71]
而是把依赖的jar包都放到了lib下，能解释一下么？

**Comment by Jamling** [comment]
@kenshinji 那是因为我其实第一次使用idea来开发，我都不好意思告诉你，我不会在idea中使用maven。

**Comment by kenshinji** [comment]
@Jamling 好的，回头我有空试试给你提个PR :)

**Comment by Jamling** [comment]
@kenshinji 谢谢～主要是核心的smartim库没有push到maven，在大陆上传太费事了。

**Comment by Jamling** [comment]
> @Jamling 好的，回头我有空试试给你提个PR :)
> btw，你的项目很有意思

这么多年了，你也没有提PR，算啦，我跳过Maven直接使用Gradle了。
