### ISSUE TITLE
微信登录扫码后无法跳转

### ISSUE THREAD

**Issue by collie2nd** [Jamling/SmartIM4IntelliJ#72]
![](http://ww4.sinaimg.cn/large/006tNc79gy1g4dh6knijej305l06ymyl.jpg)

这个错误代码也看不太懂是什么意思

**Comment by Jamling** [comment]
账号异常了，你可以使用微信网页版登录一下，应该是微信限制账号登录了。

**Comment by Jamling** [comment]
3.x已使用PC微信协议，插件王者归来
