### ISSUE TITLE
微信无法登录，扫码后报：java.lang.NumberFormatException:null

### ISSUE THREAD

**Issue by ssdutnowind** [Jamling/SmartIM4IntelliJ#74]
RT

**Comment by Jamling** [comment]
你的账号被微信限制登录了，可以在微信官方的网页版扫码登录获取详细的限制原因

**Comment by ssdutnowind** [comment]
为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

不让我用网页版微信啊……

**Comment by ssdutnowind** [comment]
> 你的账号被微信限制登录了，可以在微信官方的网页版扫码登录获取详细的限制原因

为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

这是不让我用网页版微信啊T_T

**Comment by Jamling** [comment]
不知道你的微信是否做过啥异常的事。如果没有。过段时间再看看吧。一般是一个月。

**Comment by ssdutnowind** [comment]
恩，以前应该是没登录过微信网页版，平时都是手机或Windows版。

**Comment by Jamling** [comment]
似乎新注册的微信账号也不能登录网页版

**Comment by YunniWeng** [comment]
怎么办？我的也不能登录

**Comment by Jamling** [comment]
微信不提供解除登录限制功能，只能等自动解除限制，或者等微信推出解除限制登录操作。

**Comment by ssdutnowind** [comment]
估计是微信慢慢封网页登录渠道吧，昨天找了好几个人都无法登录。

**Comment by Jamling** [comment]
@ssdutnowind 有这种可能

**Comment by zghnzch** [comment]
我得qq和微信都是 这个 null

**Comment by Jamling** [comment]
@zghnzch qq已被腾讯停止服务了。微信是由于你的账号被限制登录了。可以在官方的微信网页版 登录查看详细原因

**Comment by Houtx** [comment]
感觉这个插件要废了...

**Comment by kylin-hou** [comment]
无法登录

**Comment by AlanViast** [comment]
尝试下

```
微信

微信需加JVM运行参数

找到你的IDE所在的安装目录下的bin文件夹，打开，找到你的exe运行参数文件，如(idea64.exe.vmoptions，studio64.exe.vmoptions）使用文件编辑器打开此文件，在最后一行添加-Djsse.enableSNIExtension=false保存后重启IDE即可。

也可以通过exe快捷方式添加参数，如快捷方式目标指向：E:\Android\eclipse\eclipse.exe -nl=en -Djsse.enableSNIExtension=false，注意这种方式要求exe所在的路径不能带空格。
```

我修改完后可以用了

**Comment by kylin-hou** [comment]
> 尝试下
> 
> ```
> 微信
> 
> 微信需加JVM运行参数
> 
> 找到你的IDE所在的安装目录下的bin文件夹，打开，找到你的exe运行参数文件，如(idea64.exe.vmoptions，studio64.exe.vmoptions）使用文件编辑器打开此文件，在最后一行添加-Djsse.enableSNIExtension=false保存后重启IDE即可。
> 
> 也可以通过exe快捷方式添加参数，如快捷方式目标指向：E:\Android\eclipse\eclipse.exe -nl=en -Djsse.enableSNIExtension=false，注意这种方式要求exe所在的路径不能带空格。
> ```
> 
> 我修改完后可以用了


> 尝试下
> 
> ```
> 微信
> 
> 微信需加JVM运行参数
> 
> 找到你的IDE所在的安装目录下的bin文件夹，打开，找到你的exe运行参数文件，如(idea64.exe.vmoptions，studio64.exe.vmoptions）使用文件编辑器打开此文件，在最后一行添加-Djsse.enableSNIExtension=false保存后重启IDE即可。
> 
> 也可以通过exe快捷方式添加参数，如快捷方式目标指向：E:\Android\eclipse\eclipse.exe -nl=en -Djsse.enableSNIExtension=false，注意这种方式要求exe所在的路径不能带空格。
> ```
> 
> 我修改完后可以用了

-Djsse.enableSNIExtension=false 我添加了，但是依然报这个错
如果我在快捷方式中添加：D:\app\ideaIU-2019.1.win\bin\idea64.exe -Djsse.enableSNIExtension=false
启动报错：Cannot find file 'D:\app\ideaIU-2019.1.win\bin\-Djsse.enableSNIExtension=false'
我的ieda版本：2019.1

**Comment by Jamling** [comment]
怎么少了idea64.exe？请仔细检查一下快捷方式
