### ISSUE TITLE
找不到最新版，idea中看到的还是2.7.1 ---v2.7.2 2019-08-15，修复微信登录时的NumberFormatException

### ISSUE THREAD

**Issue by kylin-hou** [Jamling/SmartIM4IntelliJ#75]

**Comment by AlanViast** [comment]
[https://github.com/Jamling/SmartIM4IntelliJ/issues/74#issuecomment-522831644](https://github.com/Jamling/SmartIM4IntelliJ/issues/74#issuecomment-522831644)
尝试下这个方式

**Comment by Jamling** [comment]
@kylin-hou 是真爱啊，8.13提交的审核，一般是2天审核完毕，结果现在都一周了，还没有审核。所以idea中看不到最新的版本。
PS，NumberFormatException一般是账号被限制登录引起的。可以先去微信官网登录一下。如果确实是。那本插件一样也登录不上
