### ISSUE TITLE
为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登

### ISSUE THREAD

**Issue by hacpai** [Jamling/SmartIM4IntelliJ#77]
第一次使用, 报了这个错误. 请问是什么问题呢?

```
为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登
```

**Comment by Jamling** [comment]
你的账号被微信限制登录微信网页版了。

**Comment by hacpai** [comment]
@Jamling 可以申诉或者有其他办法解决吗? 不应该被限制, 这个账号我也就正常使用

**Comment by Jamling** [comment]
没有申诉途径，我猜测微信是要慢慢地停止网页版服务。终有一天，微信网页版也会走上web qq的老路。

**Comment by hacpai** [comment]
@Jamling 这就很尴尬了. 对于电脑不让安装微信客户端的用户来说, 有什么解决办法吗

**Comment by Jamling** [comment]
@hacpai 使用网页版，如果不能使用（比如你）那么就要寻找支持PC协议的版本。

**Comment by hacpai** [comment]
@Jamling 网页版也同样报错. PC 协议版本要看看了...

**Comment by cfrzjj** [comment]
我也碰到这个问题，那这款插件迟点是用不了了还是准备换微信其他登录接口？

**Comment by Jamling** [comment]
@cfrzjj 现在微信正在慢慢限制网页版，怪我没有好好宣传本插件，如果以前登录过，现在就不会被限制了。
目前本人精力有限（要花大量的时间与精力），暂无换PC接口的计划

**Comment by dabao0903** [comment]
> @Jamling 这就很尴尬了. 对于电脑不让安装微信客户端的用户来说, 有什么解决办法吗

请问，这个问题解决了吗？还是说，网页版登录的问题已经GG了

**Comment by Jamling** [comment]
> > @Jamling 这就很尴尬了. 对于电脑不让安装微信客户端的用户来说, 有什么解决办法吗
> 
> 请问，这个问题解决了吗？还是说，网页版登录的问题已经GG了

原来登录过网页版的似乎还可以登录，未登录过或长时间未登录过的，似乎都被限制登录了。

**Comment by Jamling** [comment]
在插件换协议之前，没有办法解决登录问题。QQ和微信都是一样。希望广大gay友能找到可用的替代协议

**Comment by dabao0903** [comment]
> 在插件换协议之前，没有办法解决登录问题。QQ和微信都是一样。希望广大gay友能找到可用的替代协议

谢谢作者回复，期待神通广大的gay友出手

**Comment by dabao0903** [comment]
请问这里网页开发文档，可以解决这个问题吗？

**Comment by dabao0903** [comment]
请问这里网页开发文档，可以解决这个问题吗？
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

**Comment by Carlos920** [comment]
是否能够模拟Linux环境，好像在Linux上是可以用网页登录的

**Comment by Jamling** [comment]
> 是否能够模拟Linux环境，好像在Linux上是可以用网页登录的@Jamling

确定？如果是的话，可以抓包分析一下

**Comment by Carlos920** [comment]
> > 是否能够模拟Linux环境，好像在Linux上是可以用网页登录的@Jamling
> 
> 确定？如果是的话，可以抓包分析一下

UOS上是微信官方封装的网页版微信客户端，用的electron
,archlinux可以使用这个（uos似乎有官方验证的限制）

**Comment by dabao0903** [comment]
看来有希望可以重启smartIM了

**Comment by Jamling** [comment]
> 看来有希望可以重启smartIM了

何以见得？

**Comment by zexindai** [comment]
> 是否能够模拟Linux环境，好像在Linux上是可以用网页登录的@Jamling

linux是也不行...原先有个electron的项目现在也停了

**Comment by anran-world** [comment]
现在可以直接下载qq浏览器了，左侧快捷栏直接有微信可以登录

**Comment by Jamling** [comment]
3.x已使用PC微信协议，插件王者归来
