### ISSUE TITLE
请求的名称有效，但是找不到请求的类型的数据。 (s.web2.qq.com)

### ISSUE THREAD

**Issue by jiansite** [Jamling/SmartIM4IntelliJ#78]
QQ登陆：
请求的名称有效，但是找不到请求的类型的数据。 (s.web2.qq.com)
SmartIM 2.7.2
IntelliJ IDEA 2019.3.1 (Ultimate Edition)

**Comment by jiansite** [comment]
java.net.UnknownHostException: 请求的名称有效，但是找不到请求的类型的数据。 (s.web2.qq.com)

**Comment by Jamling** [comment]
QQ于2019.01.01已正式停止服务。

**Comment by miyouzi** [comment]
换其他协议有希望吗，有开源的项目是否能参考看看？ [go-cqhttp](https://github.com/Mrs4s/go-cqhttp)
