### ISSUE TITLE
可否兼容UOS微信，之前不可以登录网页版的也可以登录了。

### ISSUE THREAD

**Issue by caoler** [Jamling/SmartIM4IntelliJ#81]
参考：
https://github.com/BlueSky-07/wechat-token

**Comment by Jamling** [comment]
这玩意儿我不会啊

**Comment by bestK** [comment]
@Jamling 

https://github.com/adamyi/wechrome/blob/6957596348979c638b300369bc61ee8960737e03/background.js#L1

**Comment by Jamling** [comment]
@bestK 试过了，还是提示
由于安全原因，此微信号不能使用网页版微信。你可以前往微信官网 https://weixin.qq.com/ 下载客户端登录。

**Comment by Jamling** [comment]
3.x已使用PC微信协议，插件王者归来
