### ISSUE TITLE
2024最新版扫码后报错

### ISSUE THREAD

**Issue by okxxcok** [Jamling/SmartIM4IntelliJ#92]
java.lang.NullPointerException: url == null

**Comment by Jamling** [comment]
有没有更详细的信息？可以从idea日志中捞下具体的日志信息

**Comment by horrzs** [comment]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cn.ieclipse.smartim.actions.HideContactAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cn.ieclipse.smartqq.intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by peter5925** [comment]
![image](https://github.com/Jamling/SmartIM4IntelliJ/assets/86543559/2330cd00-2b19-4589-bf79-704e68076fb5)

**Comment by lihuifu3306** [comment]
我也是这个问题，idea版本是2023.3.4日

**Comment by lihuifu3306** [comment]
扫描后点击登录，出现这个。idea的log日志里面没有发现报错信息

**Comment by lihuifu3306** [comment]
![微信图片_20240507114456](https://github.com/Jamling/SmartIM4IntelliJ/assets/51349645/bac2b4ae-158d-4e8c-9039-ecc464772052)

**Comment by lihuifu3306** [comment]
解决了，因为我电脑登录了微信导致的

**Comment by zuoniddemeng** [comment]
![image](https://github.com/Jamling/SmartIM4IntelliJ/assets/86471879/80f91b36-7211-4f30-a659-939df2e35cd7)
我的IDEA版本2023.2.5，Mac上无法登录进去，退出微信了也一样无法进入

**Comment by zuoniddemeng** [comment]
扫码后第一个弹窗
![image](https://github.com/Jamling/SmartIM4IntelliJ/assets/86471879/bda8872c-9c1f-42f5-8861-f60f1066407e)
然后点击登录
![image](https://github.com/Jamling/SmartIM4IntelliJ/assets/86471879/003ea6af-fdaa-4157-beaf-9ee21af3a805)
手机是IPhone13，电脑是MacBook Pro 2020

**Comment by flySnail-jinx** [comment]
BUG两个月了，来了解一下修复进度

**Comment by Jamling** [comment]
See #102
