### ISSUE TITLE
报错了，无法登录

### ISSUE THREAD

**Issue by hui0079** [Jamling/SmartIM4IntelliJ#98]
扫描后报了nullexception，无法登录，idea版本2023.2

**Comment by Jamling** [comment]
把日志贴出来

**Comment by xjbo** [comment]
java.lamg lhllPointerException
url= mull

**Comment by tabular-rasa** [comment]
加一 有啥解决办法 貌似退出后二次登陆就会出现

**Comment by Jamling** [comment]
没有日志，没法分析哇

**Comment by hui0079** [comment]
![1724140643588](https://github.com/user-attachments/assets/aa70465a-fbd7-42fa-9d2c-2ebada697775)
报错信息只有这个

**Comment by yanceysong** [comment]
同样的问题，我下载smart的swing版本发出来日志了

**Comment by Jamling** [comment]
See #102
