### ISSUE TITLE
可以调节字体大小吗

### ISSUE THREAD

**Issue by Rago-c** [Jamling/SmartIM4IntelliJ#99]
rt

**Comment by Jamling** [comment]
可以的，只要你熟悉CSS，聊天样式都可以修改

**Comment by Rago-c** [comment]
> 可以的，只要你熟悉CSS，聊天样式都可以修改

是修改.idea/下的smartIM.css吗，我修改了font-size，但是好像没有生效

**Comment by Jamling** [comment]
> > 可以的，只要你熟悉CSS，聊天样式都可以修改
> 
> 是修改.idea/下的smartIM.css吗，我修改了font-size，但是好像没有生效

尴尬，早期的版本是支持的，忘了最近的两个版本，我禁用了此功能。
